import { Board } from '../types/board';

export const UntouchedBoard: Board = {
  a1: {
    name: 'rook',
    color: 'white',
    iconName: 'white_rook.svg',
    untouched: true,
  },
  b1: {
    name: 'knight',
    color: 'white',
    iconName: 'white_knight.svg',
    untouched: true,
  },
  c1: {
    name: 'bishop',
    color: 'white',
    iconName: 'white_bishop.svg',
    untouched: true,
  },
  d1: {
    name: 'queen',
    color: 'white',
    iconName: 'white_queen.svg',
    untouched: true,
  },
  e1: {
    name: 'king',
    color: 'white',
    iconName: 'white_king.svg',
    untouched: true,
  },
  f1: {
    name: 'bishop',
    color: 'white',
    iconName: 'white_bishop.svg',
    untouched: true,
  },
  g1: {
    name: 'knight',
    color: 'white',
    iconName: 'white_knight.svg',
    untouched: true,
  },
  h1: {
    name: 'rook',
    color: 'white',
    iconName: 'white_rook.svg',
    untouched: true,
  },
  a2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  b2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  c2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  d2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  e2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  f2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  g2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  h2: {
    name: 'pawn',
    color: 'white',
    iconName: 'white_pawn.svg',
    untouched: true,
  },
  a3: null,
  b3: null,
  c3: null,
  d3: null,
  e3: null,
  f3: null,
  g3: null,
  h3: null,
  a4: null,
  b4: null,
  c4: null,
  d4: null,
  e4: null,
  f4: null,
  g4: null,
  h4: null,
  a5: null,
  b5: null,
  c5: null,
  d5: null,
  e5: null,
  f5: null,
  g5: null,
  h5: null,
  a6: null,
  b6: null,
  c6: null,
  d6: null,
  e6: null,
  f6: null,
  g6: null,
  h6: null,
  a7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  b7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  c7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  d7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  e7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  f7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  g7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  h7: {
    name: 'pawn',
    color: 'black',
    iconName: 'black_pawn.svg',
    untouched: true,
  },
  a8: {
    name: 'rook',
    color: 'black',
    iconName: 'black_rook.svg',
    untouched: true,
  },
  b8: {
    name: 'knight',
    color: 'black',
    iconName: 'black_knight.svg',
    untouched: true,
  },
  c8: {
    name: 'bishop',
    color: 'black',
    iconName: 'black_bishop.svg',
    untouched: true,
  },
  d8: {
    name: 'queen',
    color: 'black',
    iconName: 'black_queen.svg',
    untouched: true,
  },
  e8: {
    name: 'king',
    color: 'black',
    iconName: 'black_king.svg',
    untouched: true,
  },
  f8: {
    name: 'bishop',
    color: 'black',
    iconName: 'black_bishop.svg',
    untouched: true,
  },
  g8: {
    name: 'knight',
    color: 'black',
    iconName: 'black_knight.svg',
    untouched: true,
  },
  h8: {
    name: 'rook',
    color: 'black',
    iconName: 'black_rook.svg',
    untouched: true,
  },
} as const;
