import { Board } from "../types/board";

export const EmptyBoard: Board = {
  a1: { name: 'rook', color: 'white' },
  b1: { name: 'knight', color: 'white' },
  c1: { name: 'bishop', color: 'white' },
  d1: { name: 'queen', color: 'white' },
  e1: { name: 'king', color: 'white' },
  f1: { name: 'bishop', color: 'white' },
  g1: { name: 'knight', color: 'white' },
  h1: { name: 'rook', color: 'white' },
  a2: { name: 'pawn', color: 'white' },
  b2: { name: 'pawn', color: 'white' },
  c2: { name: 'pawn', color: 'white' },
  d2: { name: 'pawn', color: 'white' },
  e2: { name: 'pawn', color: 'white' },
  f2: { name: 'pawn', color: 'white' },
  g2: { name: 'pawn', color: 'white' },
  h2: { name: 'pawn', color: 'white' },
  a3: null, b3: null, c3: null, d3: null, e3: null, f3: null, g3: null, h3: null,
  a4: null, b4: null, c4: null, d4: null, e4: null, f4: null, g4: null, h4: null,
  a5: null, b5: null, c5: null, d5: null, e5: null, f5: null, g5: null, h5: null,
  a6: null, b6: null, c6: null, d6: null, e6: null, f6: null, g6: null, h6: null,
  a7: { name: 'pawn', color: 'black' },
  b7: { name: 'pawn', color: 'black' },
  c7: { name: 'pawn', color: 'black' },
  d7: { name: 'pawn', color: 'black' },
  e7: { name: 'pawn', color: 'black' },
  f7: { name: 'pawn', color: 'black' },
  g7: { name: 'pawn', color: 'black' },
  h7: { name: 'pawn', color: 'black' },
  a8: { name: 'rook', color: 'black' },
  b8: { name: 'knight', color: 'black' },
  c8: { name: 'bishop', color: 'black' },
  d8: { name: 'queen', color: 'black' },
  e8: { name: 'king', color: 'black' },
  f8: { name: 'bishop', color: 'black' },
  g8: { name: 'knight', color: 'black' },
  h8: { name: 'rook', color: 'black' }
} as const;
